name: CI & Despliegue a GitHub Pages

on:
  push:
    branches: ["main", "frontend"] # Se activa con cada push a la rama 'main'
  pull_request:
    branches: ["main"] # También se activa con cada Pull Request
  workflow_dispatch: # Permite ejecución manual

concurrency:
  group: 'CI-CD-GHPages'
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: 'hello world'
        run: echo "Hello, world!"
      - name: fecha
        run: date
      - name: muestreme el contenido del directorio
        run: |
          ls -la